app:
  jwt:
    secret: "v-duzhe-sekretniy-kluch-yakiy-mae-buty-dovgym-i-skladnym"
    expiration-ms: 3600000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sezdb
    username: andruf
    password: andruf

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "1064163809348-7b9njo94mhr9f5ke96o8enom4mmp32ad.apps.googleusercontent.com"
            client-secret: "ВАШ_СЕКРЕТ_ТУТ"

  mail:
    host: smtp.gmail.com
    port: 587
    username: teachly.sup@gmail.com
    password: "lwuhzuubkjzuznyu"

